// 需要构造的数据
const test = [
  {
    examinationData: {
      researchUnitCode: undefined,
      ptdtTabName: "SCREENING",
      ptdeid: 2,
      ptdtCheckDate: "2023-04-11",
      ptdtWeight: 55,
      ptdtHeight: 173,
      ptdtDosage: "85 MBq",
      ptdtInjectionTime: "18:24",
      ptdtScanTime: "22:16",
      ptdtBloodglucose: "4.5",
      ptdtDjDoctor: "注射护士",
    },
    evaluationData: {
      isEditing: false,
      mediastinumSuv: 10.1,
      liverSuv: 10.2,
      evidence: 2,
      lesionLocation: "简单的位置",
      lesionSuv: 10.3,
      // 这里有一个简单的交互
      iugano5ps: 4,
      lesionCompare: 2,
      isNewLesion: 0,
      isLesionConsistent: 0,
      // 这里有一个简单的交互
      comment: "placeHolder",
      basedPetScan: 4,
      assYirc: 2,
      assOverallResponse: 4,
    },
  },
  {
    examinationData: {
      researchUnitCode: undefined,
      ptdtTabName: "WEEK 1",
      ptdeid: 1,
      ptdtCheckDate: "2023-04-11",
      ptdtWeight: 55,
      ptdtHeight: 173,
      ptdtDosage: "85 MBq",
      ptdtInjectionTime: "18:24",
      ptdtScanTime: "22:16",
      ptdtBloodglucose: "4.5",
      ptdtDjDoctor: "注射护士",
    },
    evaluationData: undefined,
  },
  {
    examinationData: {
      researchUnitCode: undefined,
      ptdtTabName: "WEEK 2",
      ptdeid: 1,
      ptdtCheckDate: "2023-04-11",
      ptdtWeight: 55,
      ptdtHeight: 173,
      ptdtDosage: "85 MBq",
      ptdtInjectionTime: "18:24",
      ptdtScanTime: "22:16",
      ptdtBloodglucose: "4.5",
      ptdtDjDoctor: "注射护士",
    },
    evaluationData: {
      isEditing: false,
      mediastinumSuv: 10.1,
      liverSuv: 10.2,
      evidence: 1,
      lesionLocation: "week 2",
      lesionSuv: 10.3,
      // 这里有一个简单的交互
      iugano5ps: 3,
      lesionCompare: 6,
      isNewLesion: 0,
      isLesionConsistent: 0,
      // 这里有一个简单的交互
      comment: "placeHolder",
      basedPetScan: 4,
      assYirc: 2,
      assOverallResponse: 2,
    },
  },
];
